name: router1_app_mvp
description: Router1 MVP app for Keenetic customers.
publish_to: "none"
version: 0.2.0-internal.3+102

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.7
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  path_provider: ^2.1.6
  share_plus: ^13.2.0
  file_saver: ^0.2.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/illustrations/
    - assets/icons/
    - assets/animations/
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope-ExtraBold.ttf
          weight: 800
